apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    io.kompose.service: cep-temperature1
  name: cep-temperature1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cep-temperature1
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/simulateiot: "true"
        io.kompose.service: cep-temperature1
    spec:
      containers:
        - image: raaulcs/tfg:esper-temperature1
          name: cep-temperature1
          resources: {}
      restartPolicy: Always
status: {}
