apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: mosquitto-temperature1
  name: mosquitto-temperature1
spec:
  type: NodePort
  ports:
    - protocol: TCP
      name: "1885"
      port: 1885
      targetPort: 1883
  selector:
    io.kompose.service: mosquitto-temperature1
status:
  loadBalancer: {}

