apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: actuator-actgas3
  name: actuator-actgas3
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: actuator-actgas3
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/simulateiot: "true"
        io.kompose.service: actuator-actgas3
    spec:
      containers:
        - image: raaulcs/tfg:actuator-actgas3
          name: actuator-actgas3
          resources: {}
      restartPolicy: Always
status: {}

