apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    io.kompose.service: cep-water2
  name: cep-water2
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cep-water2
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/simulateiot: "true"
        io.kompose.service: cep-water2
    spec:
      containers:
        - image: raaulcs/tfg:esper-water2
          name: cep-water2
          resources: {}
      restartPolicy: Always
status: {}
