apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: mosquitto-presence0
  name: mosquitto-presence0
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mosquitto-presence0
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/simulateiot: "true"
        io.kompose.service: mosquitto-presence0
    spec:
      containers:
        - image: raaulcs/tfg:eclipse-mosquitto-configured
          name: mosquitto-presence0
          ports:
            - containerPort: 1883
          resources: {}
      restartPolicy: Always
status: {}

