apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: mosquitto-water2
  name: mosquitto-water2
spec:
  type: NodePort
  ports:
    - protocol: TCP
      name: "1886"
      port: 1886
      targetPort: 1883
  selector:
    io.kompose.service: mosquitto-water2
status:
  loadBalancer: {}

