apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: sensor-sensgas3
  name: sensor-sensgas3
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: sensor-sensgas3
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/simulateiot: "true"
        io.kompose.service: sensor-sensgas3
    spec:
      containers:
        - image: raaulcs/tfg:sensor-sensgas3
          name: sensor-sensgas3
          resources: {}
      restartPolicy: Always
status: {}
