apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: sensor-senswater2
  name: sensor-senswater2
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: sensor-senswater2
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/simulateiot: "true"
        io.kompose.service: sensor-senswater2
    spec:
      containers:
        - image: raaulcs/tfg:sensor-senswater2
          name: sensor-senswater2
          resources: {}
      restartPolicy: Always
status: {}
