apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: sensor-sensbrightness1
  name: sensor-sensbrightness1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: sensor-sensbrightness1
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/simulateiot: "true"
        io.kompose.service: sensor-sensbrightness1
    spec:
      containers:
        - image: raaulcs/tfg:sensor-sensbrightness1
          name: sensor-sensbrightness1
          resources: {}
      restartPolicy: Always
status: {}
