apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: actuator-acthumidity0
  name: actuator-acthumidity0
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: actuator-acthumidity0
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/simulateiot: "true"
        io.kompose.service: actuator-acthumidity0
    spec:
      containers:
        - image: raaulcs/tfg:actuator-acthumidity0
          name: actuator-acthumidity0
          resources: {}
      restartPolicy: Always
status: {}

