apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: sensor-senstemperature1
  name: sensor-senstemperature1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: sensor-senstemperature1
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/simulateiot: "true"
        io.kompose.service: sensor-senstemperature1
    spec:
      containers:
        - image: raaulcs/tfg:sensor-senstemperature1
          name: sensor-senstemperature1
          resources: {}
      restartPolicy: Always
status: {}
