apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: sensor-senswaterlevel2
  name: sensor-senswaterlevel2
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: sensor-senswaterlevel2
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/simulateiot: "true"
        io.kompose.service: sensor-senswaterlevel2
    spec:
      containers:
        - image: raaulcs/tfg:sensor-senswaterlevel2
          name: sensor-senswaterlevel2
          resources: {}
      restartPolicy: Always
status: {}
