apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    io.kompose.service: fogb0
  name: fogb0
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: fogb0
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/simulateiot: "true"
        io.kompose.service: fogb0
    spec:
      containers:
        - image: raaulcs/tfg:fogb0
          name: fogb0
          resources: {}
      restartPolicy: Always
status: {}
