apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: mosquitto-foga0
  name: mosquitto-foga0
spec:
  type: NodePort
  ports:
    - protocol: TCP
      name: "1884"
      port: 1884
      targetPort: 1883
  selector:
    io.kompose.service: mosquitto-foga0
status:
  loadBalancer: {}

