apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: sensor-sensa0
  name: sensor-sensa0
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: sensor-sensa0
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/simulateiot: "true"
        io.kompose.service: sensor-sensa0
    spec:
      containers:
        - image: raaulcs/tfg:sensor-sensa0
          name: sensor-sensa0
          resources: {}
      restartPolicy: Always
status: {}
