apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: sensor-sensb0
  name: sensor-sensb0
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: sensor-sensb0
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/simulateiot: "true"
        io.kompose.service: sensor-sensb0
    spec:
      containers:
        - image: raaulcs/tfg:sensor-sensb0
          name: sensor-sensb0
          resources: {}
      restartPolicy: Always
status: {}
